.TH "/home/Theo/Téléchargements/sae/SAE_JEU/MinGL2_IUT_AIX-master/src/exception/cexception.cpp" 3 "Fri Jan 10 2025" "SAE 1.01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/SAE_JEU/MinGL2_IUT_AIX-master/src/exception/cexception.cpp \- classe CException  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'mingl/exception/cexception\&.h'\fP
.br

.SH "Detailed Description"
.PP 
classe CException 


.PP
\fBAuthors\fP
.RS 4
M\&. Laporte, D\&. Mathieu
.RE
.PP
\fBDate\fP
.RS 4
23/03/2010
.RE
.PP
\fBVersion\fP
.RS 4
V1\&.0 
.RE
.PP

.PP
Definition in file \fBcexception\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SAE 1\&.01 from the source code\&.
