.TH "/home/Theo/Téléchargements/sae/SAE_JEU/sprites/cigarette.h" 3 "Fri Jan 10 2025" "SAE 1.01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/SAE_JEU/sprites/cigarette.h \- Affiche le sprite d'une cigarette\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mingl/shape/rectangle\&.h'\fP
.br
\fC#include 'mingl/shape/oval\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBCigarette\fP (\fBMinGL\fP &window, int startX, int startY, int scaleX, int scaleY)"
.br
.RI "cette fonction dessine une cigarette "
.in -1c
.SH "Detailed Description"
.PP 
Affiche le sprite d'une cigarette\&. 


.PP
\fBAuthor\fP
.RS 4
Matisse Quilliec 
.RE
.PP
\fBDate\fP
.RS 4
December 2024 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBcigarette\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void Cigarette (\fBMinGL\fP & window, int startX, int startY, int scaleX, int scaleY)"

.PP
cette fonction dessine une cigarette 
.PP
\fBParameters\fP
.RS 4
\fIwindow\fP Référence à l'objet \fBMinGL\fP pour dessiner les formes\&. 
.br
\fIstartX\fP Position x du coin supérieur gauche de la cigarette\&. 
.br
\fIstartY\fP Position y du coin supérieur gauche de la cigarette\&. 
.br
\fIscaleX\fP Facteur d'échelle pour la longueur et la taille horizontale des éléments\&. 
.br
\fIscaleY\fP Facteur d'échelle pour la largeur et la taille verticale des éléments\&. 
.RE
.PP

.PP
Definition at line \fB25\fP of file \fBcigarette\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SAE 1\&.01 from the source code\&.
