.TH "/home/Theo/Téléchargements/sae/SAE_JEU/MinGL2_IUT_AIX-master/include/mingl/macros.h" 3 "Fri Jan 10 2025" "SAE 1.01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/SAE_JEU/MinGL2_IUT_AIX-master/include/mingl/macros.h \- Macros utiles\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUNUSED\fP(x)   (void)(x)"
.br
.RI "Une macro permettant de marquer explicitement un paramètre de fonction comme étant inutilisé "
.in -1c
.SH "Detailed Description"
.PP 
Macros utiles\&. 


.PP
\fBAuthor\fP
.RS 4
Alexandre Sollier 
.RE
.PP
\fBDate\fP
.RS 4
Janvier 2020 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBmacros\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define UNUSED(x)   (void)(x)"

.PP
Une macro permettant de marquer explicitement un paramètre de fonction comme étant inutilisé 
.PP
Definition at line \fB17\fP of file \fBmacros\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SAE 1\&.01 from the source code\&.
