.TH "md__home__theo__t_xC3_xA9l_xC3_xA9chargements_sae__s_a_e__j_e_u__min_g_l2__i_u_t__a_i_x_master_examples__r_e_a_d_m_e" 3 "Fri Jan 10 2025" "SAE 1.01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home__theo__t_xC3_xA9l_xC3_xA9chargements_sae__s_a_e__j_e_u__min_g_l2__i_u_t__a_i_x_master_examples__r_e_a_d_m_e \- Exemples minGL 2 
Ce répertoire contient divers exemples dont le but est de vous aider a utiliser minGL 2\&. 
.br
 Il est conseillé de \fBbien\fP lire les commentaires qui sont éparpillés dans le code de ces exemples, et de lire la documentation des différentes classes qui vous sont introduites en même temps\&.
.SH "<tt>00-Boilerplate/</tt>"
.PP
L'exemple n°00 Boilerplate contient le strict minimum pour démarrer un projet sous minGL 2\&.
.PP
Si vous voulez démarrer un projet avec l'aide de cet exemple, il vous est vivement conseillé de le placer dans un répertoire séparé de minGL 2, de placer le répertoire de minGL 2 dans votre nouveau répertoire de travail et de mettre a jour le fichier de projet \fC00-Boilerplate\&.pro\fP en accord avec vos changements\&.
.SH "<tt>01-Shapes/</tt>"
.PP
L'exemple n°01 Shapes vous montre comment dessiner des formes géométriques sur la fenêtre avec minGL 2\&.
.PP
Vous y verrez certaines classes utilisées très souvent lors de l'utilisation de la bibliothèque, ainsi que les mécanismes d'affichage\&.
.SH "<tt>02-Texte/</tt>"
.PP
L'exemple n°02 Texte vous montre comment afficher du texte a l'utilisateur directement sur la fenêtre\&.
.PP
Les différents paramètres pour afficher le texte vous y seront montrés\&.
.SH "<tt>03-Clavier/</tt>"
.PP
L'exemple n°03 Clavier vous montre comment récupérer l'état d'une touche du clavier\&.
.PP
La carré bleu peut être déplacé a l'aide des touches ZQSD du clavier\&.
.SH "<tt>04-Souris/</tt>"
.PP
L'exemple n°4 Souris vous montre comment se servir du gestionnaire d'évènements pour récupérer des évènements souris\&.
.PP
Le carré bleu peut être déplacé a l'aide du curseur de la souris\&. Sa couleur est changé au clic de souris\&. 
.br
 \fBAttention:\fP Comme nous nous servons du gestionnaire d'évènements, la ligne suivante, provenant du Boilerplate, et permettant de vider le gestionnaire d'évènement périodiquement, a été commentée: 
.PP
.nf
 {C++}
window\&.getEventManager()\&.clearEvents();

.fi
.PP
.SH "<tt>05-Transition/</tt>"
.PP
L'exemple n°5 Transition vous montre comment se servir du gestionnaire de transition\&.
.PP
Plusieurs formes géométriques ont des transitions qui sont appliquées sur leur différentes propriétés, avec des paramètres qui diffèrent afin que vous puissiez voir ses possibilités\&.
.SH "<tt>06-Sprite/</tt>"
.PP
L'exemple n°6 Sprite vous montre comment charger une image externe au format \&.si2 dans votre programme\&.
.PP
Cet exemple stocke les ressources dans le répertoire \fCres/\fP, qui comprend actuellement une unique image\&. 
.br
 Afin que le programme puisse retrouver ses ressources, ce répertoire doit \fBimpérativement\fP être copié dans le même répertoire où se trouve l'exécutable\&.
.SH "<tt>07-Audio/</tt>"
.PP
L'exemple n°7 Audio vous montre comment utiliser le sous-système audio afin de jouer de la musique et des effets sonores\&.
.PP
Même remarque que l'exemple précédent, le répertoire \fCres/\fP doit être copié dans le même répertoire que celui où se trouve l'exécutable\&.
.SS "Remerciements"
.IP "\(bu" 2
\fBmusic\&.wav\fP 
.br
 The Entertainer by Kevin MacLeod 
.br
 Link: https://incompetech.filmmusic.io/song/5765-the-entertainer 
.br
 License: http://creativecommons.org/licenses/by/4.0/ 
.br

.IP "\(bu" 2
\fBsound1\&.wav\fP 
.br
 snr_bod\&.wav by DWSD 
.br
 Link: https://freesound.org/people/DWSD/sounds/183111 
.br
 License: https://creativecommons.org/licenses/by/3.0/
.IP "\(bu" 2
\fBsound2\&.wav\fP 
.br
 metalbang0\&.wav by SamsterBirdies 
.br
 Link: https://freesound.org/people/SamsterBirdies/sounds/435699 
.br
 License: https://creativecommons.org/publicdomain/zero/1.0/ 
.br

.PP
.SH "<tt>08-CustomDrawable/</tt>"
.PP
L'exemple n°8 Custom Drawable vous montre comment créer vos propres objets affichables\&.
.PP
Une classe d'exemple \fC\fBBgText\fP\fP, affichant un texte avec une couleur de fond, est créé comme exemple\&.
.SH "<tt>09-CustomTransitionable/</tt>"
.PP
L'exemple n°9 Custom Transitionable vous montre comment créer vos propres objets compatible avec le gestionnaire de transition\&.
.PP
Cet exemple reprend la classe \fC\fBBgText\fP\fP créé lors de l'exemple précédent, afin de lui ajouter le support de la transition pour sa couleur de texte et de fond\&. 
