.TH "/home/Theo/Téléchargements/sae/SAE_JEU/MinGL2_IUT_AIX-master/src/mingl.cpp" 3 "Fri Jan 10 2025" "SAE 1.01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/SAE_JEU/MinGL2_IUT_AIX-master/src/mingl.cpp \- La bête\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include 'mingl/mingl\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBIND_CALLBACK\fP(HANDLER)   callBackBuilder<decltype(HANDLER), HANDLER>::callback"
.br
.in -1c
.SH "Detailed Description"
.PP 
La bête\&. 


.PP
\fBAuthor\fP
.RS 4
Alexandre Sollier, Clément Mathieu--Drif, Alain Casali 
.RE
.PP
\fBDate\fP
.RS 4
Janvier 2020 
.RE
.PP
\fBVersion\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition in file \fBmingl\&.cpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define BIND_CALLBACK(HANDLER)   callBackBuilder<decltype(HANDLER), HANDLER>::callback"

.PP
Definition at line \fB40\fP of file \fBmingl\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SAE 1\&.01 from the source code\&.
