.TH "nsEvent::MouseClickData_t" 3 "Fri Jan 10 2025" "SAE 1.01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nsEvent::MouseClickData_t \- Possède des données pour un événement MouseClick\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <event\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBbutton\fP"
.br
.ti -1c
.RI "int \fBstate\fP"
.br
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Possède des données pour un événement MouseClick\&. 
.PP
Definition at line \fB33\fP of file \fBevent\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int nsEvent::MouseClickData_t::button"
ID numérique du bouton 
.PP
Definition at line \fB34\fP of file \fBevent\&.hpp\fP\&.
.SS "int nsEvent::MouseClickData_t::state"
Nouvel état du bouton 
.PP
Definition at line \fB35\fP of file \fBevent\&.hpp\fP\&.
.SS "int nsEvent::MouseClickData_t::x"
Coordonnée X du curseur, relative au coin supérieur-gauche de la fenêtre 
.PP
Definition at line \fB36\fP of file \fBevent\&.hpp\fP\&.
.SS "int nsEvent::MouseClickData_t::y"
Coordonnée Y du curseur, relative au coin supérieur-gauche de la fenêtre 
.PP
Definition at line \fB37\fP of file \fBevent\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SAE 1\&.01 from the source code\&.
