.TH "nsShape" 3 "Fri Jan 10 2025" "SAE 1.01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nsShape \- Espace de nom pour différentes formes\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCircle\fP"
.br
.RI "Classe représentant un cercle\&. "
.ti -1c
.RI "class \fBLine\fP"
.br
.RI "Classe représentant une ligne\&. "
.ti -1c
.RI "class \fBOval\fP"
.br
.RI "Classe représentant un \fBOval\fP\&. "
.ti -1c
.RI "class \fBRectangle\fP"
.br
.RI "Classe représentant un rectangle\&. "
.ti -1c
.RI "class \fBShape\fP"
.br
.RI "Classe de base pour une forme\&. "
.ti -1c
.RI "class \fBTriangle\fP"
.br
.RI "Classe représentant un triangle\&. "
.in -1c
.SH "Detailed Description"
.PP 
Espace de nom pour différentes formes\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for SAE 1\&.01 from the source code\&.
