.TH "/home/Theo/Téléchargements/sae/SAE_JEU/MinGL2_IUT_AIX-master/include/mingl/graphics/rgbacolor.h" 3 "Fri Jan 10 2025" "SAE 1.01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/SAE_JEU/MinGL2_IUT_AIX-master/include/mingl/graphics/rgbacolor.h \- Représente une couleur RGBA\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <GL/freeglut\&.h>\fP
.br
\fC#include '\&.\&./tools/ieditable\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBnsGraphics::RGBAcolor\fP"
.br
.RI "Classe représentant un couleur RGBA8888\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBnsGraphics\fP"
.br
.RI "Espace de nom pour les utilitaires graphiques\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const RGBAcolor \fBnsGraphics::KBlack\fP { 0, 0, 0}"
.br
.ti -1c
.RI "const RGBAcolor \fBnsGraphics::KWhite\fP {255, 255, 255}"
.br
.ti -1c
.RI "const RGBAcolor \fBnsGraphics::KRed\fP {255, 0, 0}"
.br
.ti -1c
.RI "const RGBAcolor \fBnsGraphics::KLime\fP { 0, 255, 0}"
.br
.ti -1c
.RI "const RGBAcolor \fBnsGraphics::KBlue\fP { 0, 0, 255}"
.br
.ti -1c
.RI "const RGBAcolor \fBnsGraphics::KYellow\fP {255, 255, 0}"
.br
.ti -1c
.RI "const RGBAcolor \fBnsGraphics::KCyan\fP { 0, 255, 255}"
.br
.ti -1c
.RI "const RGBAcolor \fBnsGraphics::KMagenta\fP {255, 0, 255}"
.br
.ti -1c
.RI "const RGBAcolor \fBnsGraphics::KSilver\fP {192, 192, 192}"
.br
.ti -1c
.RI "const RGBAcolor \fBnsGraphics::KGray\fP {128, 128, 128}"
.br
.ti -1c
.RI "const RGBAcolor \fBnsGraphics::KDarkGray\fP {200, 200, 200}"
.br
.ti -1c
.RI "const RGBAcolor \fBnsGraphics::KMaroon\fP {128, 0, 0}"
.br
.ti -1c
.RI "const RGBAcolor \fBnsGraphics::KOlive\fP {128, 128, 0}"
.br
.ti -1c
.RI "const RGBAcolor \fBnsGraphics::KGreen\fP { 0, 128, 0}"
.br
.ti -1c
.RI "const RGBAcolor \fBnsGraphics::KPurple\fP {128, 0, 128}"
.br
.ti -1c
.RI "const RGBAcolor \fBnsGraphics::KTeal\fP { 0, 128, 128}"
.br
.ti -1c
.RI "const RGBAcolor \fBnsGraphics::KNavy\fP { 0, 0, 128}"
.br
.ti -1c
.RI "const RGBAcolor \fBnsGraphics::KBeige\fP {231, 211, 171}"
.br
.ti -1c
.RI "const RGBAcolor \fBnsGraphics::KTransparent\fP { 0, 0, 0, 0}"
.br
.ti -1c
.RI "const RGBAcolor \fBnsGraphics::KBlueTransparent\fP { 0, 0, 255, 30}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Représente une couleur RGBA\&. 


.PP
\fBAuthor\fP
.RS 4
Alexandre Sollier 
.RE
.PP
\fBDate\fP
.RS 4
Janvier 2020 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition in file \fBrgbacolor\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SAE 1\&.01 from the source code\&.
