.TH "/home/Theo/Téléchargements/sae/SAE_JEU/MinGL2_IUT_AIX-master/include/mingl/transition/transition_types.h" 3 "Fri Jan 10 2025" "SAE 1.01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/SAE_JEU/MinGL2_IUT_AIX-master/include/mingl/transition/transition_types.h \- Définit quelques types pour les transitions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <chrono>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBnsTransition\fP"
.br
.RI "Espace de nom pour le moteur de transition et ses composants\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::chrono::duration< float, std::nano > \fBnsTransition::SystemDuration_t\fP"
.br
.RI "SystemDuration_t : Définition de type stockant une durée exprimée en nanosecondes, sous forme de float\&. "
.ti -1c
.RI "typedef std::chrono::time_point< std::chrono::steady_clock, SystemDuration_t > \fBnsTransition::SystemTimePoint_t\fP"
.br
.RI "SystemTimePoint_t : Définition de type représentant un point dans le temps basée sur l'horloge système\&. "
.in -1c
.SH "Detailed Description"
.PP 
Définit quelques types pour les transitions\&. 


.PP
\fBAuthor\fP
.RS 4
Alexandre Sollier 
.RE
.PP
\fBDate\fP
.RS 4
Janvier 2020 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBtransition_types\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SAE 1\&.01 from the source code\&.
