.TH "/home/Theo/Téléchargements/sae/SAE_JEU/MinGL2_IUT_AIX-master/include/mingl/transition/transition_engine.h" 3 "Fri Jan 10 2025" "SAE 1.01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/SAE_JEU/MinGL2_IUT_AIX-master/include/mingl/transition/transition_engine.h \- Gestionnaire de transition de minGL\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <chrono>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <list>\fP
.br
\fC#include 'transition\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBnsTransition::TransitionEngine\fP"
.br
.RI "Une classe implémentant un moteur de transition supportant plusieurs transitions a la fois\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBnsTransition\fP"
.br
.RI "Espace de nom pour le moteur de transition et ses composants\&. "
.in -1c
.SH "Detailed Description"
.PP 
Gestionnaire de transition de minGL\&. 


.PP
\fBAuthor\fP
.RS 4
Alexandre Sollier 
.RE
.PP
\fBDate\fP
.RS 4
Janvier 2020 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBtransition_engine\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SAE 1\&.01 from the source code\&.
