.TH "/home/Theo/Téléchargements/sae/SAE_JEU/MinGL2_IUT_AIX-master/src/shape/triangle.cpp" 3 "Fri Jan 10 2025" "SAE 1.01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/SAE_JEU/MinGL2_IUT_AIX-master/src/shape/triangle.cpp \- Représente un triangle\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'mingl/shape/triangle\&.h'\fP
.br
\fC#include 'mingl/macros\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Représente un triangle\&. 


.PP
\fBAuthor\fP
.RS 4
Alexandre Sollier 
.RE
.PP
\fBDate\fP
.RS 4
Janvier 2020 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBtriangle\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SAE 1\&.01 from the source code\&.
