.TH "/home/Theo/Téléchargements/sae/SAE_JEU/sprites/wall.h" 3 "Fri Jan 10 2025" "SAE 1.01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/SAE_JEU/sprites/wall.h \- Affiche le sprite d'un mur\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mingl/shape/rectangle\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBWall\fP (\fBMinGL\fP &window, int Circle1, int Circle2, int mat_x, int mat_y)"
.br
.RI "cette fonction dessine un mur "
.in -1c
.SH "Detailed Description"
.PP 
Affiche le sprite d'un mur\&. 

Affiche le sprite d'un bouton\&.
.PP
\fBAuthor\fP
.RS 4
Matisse Quilliec 
.RE
.PP
\fBDate\fP
.RS 4
December 2024 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0
.RE
.PP
\fBAuthor\fP
.RS 4
Matisse Quilliec 
.RE
.PP
\fBDate\fP
.RS 4
Janvier 2025 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBwall\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void Wall (\fBMinGL\fP & window, int Circle1, int Circle2, int mat_x, int mat_y)"

.PP
cette fonction dessine un mur 
.PP
\fBParameters\fP
.RS 4
\fIwindow\fP Référence à l'objet \fBMinGL\fP pour dessiner la forme\&. 
.br
\fICircle1\fP Position x du centre du mur\&. 
.br
\fICircle2\fP Position y du centre du mur\&. 
.br
\fImat_x\fP Facteur d'échelle pour la dimension horizontale du mur\&. 
.br
\fImat_y\fP Facteur d'échelle pour la dimension verticale du mur\&. 
.RE
.PP

.PP
Definition at line \fB24\fP of file \fBwall\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SAE 1\&.01 from the source code\&.
