.TH "/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/examples Directory Reference" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/examples Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fB00\-Boilerplate\fP"
.br
.ti -1c
.RI "directory \fB01\-Shapes\fP"
.br
.ti -1c
.RI "directory \fB02\-Texte\fP"
.br
.ti -1c
.RI "directory \fB03\-Clavier\fP"
.br
.ti -1c
.RI "directory \fB04\-Souris\fP"
.br
.ti -1c
.RI "directory \fB05\-Transition\fP"
.br
.ti -1c
.RI "directory \fB06\-Sprite\fP"
.br
.ti -1c
.RI "directory \fB07\-Audio\fP"
.br
.ti -1c
.RI "directory \fB08\-CustomDrawable\fP"
.br
.ti -1c
.RI "directory \fB09\-CustomTransitionable\fP"
.br
.in -1c
