.TH "/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/audio Directory Reference" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/audio Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaudioengine\&.h\fP"
.br
.RI "Gestionnaire audio de minGL\&. "
.in -1c
