.TH "/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/src/graphics Directory Reference" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/src/graphics Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBrgbacolor\&.cpp\fP"
.br
.RI "Représente une couleur RGBA\&. "
.ti -1c
.RI "file \fBvec2d\&.cpp\fP"
.br
.RI "Représente un vecteur sur deux dimensions\&. "
.in -1c
