.TH "/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/src/event Directory Reference" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/src/event Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBevent_manager\&.cpp\fP"
.br
.RI "Gestionnaire d'événements de minGL\&. "
.in -1c
