.TH "/home/Theo/Téléchargements/sae Directory Reference" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBJeu\fP"
.br
.ti -1c
.RI "directory \fBMinGL2_IUT_AIX\-master\fP"
.br
.ti -1c
.RI "directory \fBsprites\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.in -1c
