.TH "/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/shape Directory Reference" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/shape Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcircle\&.h\fP"
.br
.RI "Représente un cercle\&. "
.ti -1c
.RI "file \fBline\&.h\fP"
.br
.RI "Représente une ligne\&. "
.ti -1c
.RI "file \fBoval\&.h\fP"
.br
.RI "Représente un oval\&. "
.ti -1c
.RI "file \fBrectangle\&.h\fP"
.br
.RI "Représente un rectangle\&. "
.ti -1c
.RI "file \fBshape\&.h\fP"
.br
.RI "Représente une forme\&. "
.ti -1c
.RI "file \fBtriangle\&.h\fP"
.br
.RI "Représente un triangle\&. "
.in -1c
