.TH "/home/Theo/Téléchargements/sae/Jeu Directory Reference" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/Jeu Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBgame\&.cpp\fP"
.br
.ti -1c
.RI "file \fBgame\&.h\fP"
.br
.RI "Set of usefull functions for the game\&. "
.ti -1c
.RI "file \fBgridmanagement\&.cpp\fP"
.br
.ti -1c
.RI "file \fBgridmanagement\&.h\fP"
.br
.RI "Set of usefull functions for the grid management\&. "
.ti -1c
.RI "file \fBMenuManagement\&.h\fP"
.br
.ti -1c
.RI "file \fBparams\&.cpp\fP"
.br
.ti -1c
.RI "file \fBparams\&.h\fP"
.br
.RI "Paramters' definition and associated functions\&. "
.ti -1c
.RI "file \fBtype\&.h\fP"
.br
.RI "Definition of usefull types or aliases for the project\&. "
.in -1c
