.TH "/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/src/gui Directory Reference" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/src/gui Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBglut_font\&.cpp\fP"
.br
.RI "Classe utilitaire pour utiliser facilement les polices de Glut\&. "
.ti -1c
.RI "file \fBsprite\&.cpp\fP"
.br
.RI "Image pouvant être chargé depuis un fichier\&. "
.ti -1c
.RI "file \fBtext\&.cpp\fP"
.br
.in -1c
