.TH "/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/examples/07-Audio Directory Reference" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/examples/07-Audio Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.in -1c
