.TH "/home/Theo/Téléchargements/sae/sprites Directory Reference" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/sprites Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbutton\&.h\fP"
.br
.ti -1c
.RI "file \fBcigarette\&.h\fP"
.br
.RI "Affiche le sprite d'une cigarette\&. "
.ti -1c
.RI "file \fBkebab\&.h\fP"
.br
.ti -1c
.RI "file \fBmonstre\&.h\fP"
.br
.ti -1c
.RI "file \fBplayer1\&.h\fP"
.br
.RI "Affiche le sprite du player 1\&. "
.ti -1c
.RI "file \fBplayer2\&.h\fP"
.br
.RI "Affiche le sprite du player 2\&. "
.ti -1c
.RI "file \fBstatue\&.h\fP"
.br
.ti -1c
.RI "file \fBteleporter\&.h\fP"
.br
.ti -1c
.RI "file \fBwall\&.h\fP"
.br
.RI "Affiche le sprite d'un bouton\&. "
.in -1c
