.TH "/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/src/shape Directory Reference" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/src/shape Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcircle\&.cpp\fP"
.br
.RI "Représente un cercle\&. "
.ti -1c
.RI "file \fBline\&.cpp\fP"
.br
.RI "Représente une ligne\&. "
.ti -1c
.RI "file \fBoval\&.cpp\fP"
.br
.RI "Représente un oval\&. "
.ti -1c
.RI "file \fBrectangle\&.cpp\fP"
.br
.RI "Représente un rectangle\&. "
.ti -1c
.RI "file \fBshape\&.cpp\fP"
.br
.RI "Représente une forme\&. "
.ti -1c
.RI "file \fBtriangle\&.cpp\fP"
.br
.RI "Représente un triangle\&. "
.in -1c
