.TH "/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/transition Directory Reference" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/transition Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBitransitionable\&.h\fP"
.br
.RI "Interface pour objet 'transitionable'\&. "
.ti -1c
.RI "file \fBtransition\&.h\fP"
.br
.RI "Definition d'une transition\&. "
.ti -1c
.RI "file \fBtransition_contract\&.h\fP"
.br
.RI "Création de la transition\&. "
.ti -1c
.RI "file \fBtransition_engine\&.h\fP"
.br
.RI "Gestionnaire de transition de minGL\&. "
.ti -1c
.RI "file \fBtransition_types\&.h\fP"
.br
.RI "Définit quelques types pour les transitions\&. "
.in -1c
