.TH "/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/src/audio/audioengine.cpp" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/src/audio/audioengine.cpp \- Gestionnaire audio de minGL\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mingl/audio/audioengine\&.h'\fP
.br
\fC#include 'mingl/exception/cexception\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Gestionnaire audio de minGL\&. 


.PP
\fBAuthor\fP
.RS 4
Clément Mathieu--Drif 
.RE
.PP
\fBDate\fP
.RS 4
Septembre 2020 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition in file \fBaudioengine\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
