.TH "/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/audio/audioengine.h" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/audio/audioengine.h \- Gestionnaire audio de minGL\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include <list>\fP
.br
\fC#include <SFML/Audio\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBnsAudio::AudioEngine\fP"
.br
.RI "Une classe de gestion des effets audio et de la musique\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBnsAudio\fP"
.br
.RI "Espace de nom pour les utilitaires audio\&. Il est conseillé d'utiliser des fichiers \&.wav\&. "
.in -1c
.SH "Detailed Description"
.PP 
Gestionnaire audio de minGL\&. 


.PP
\fBAuthor\fP
.RS 4
Clément Mathieu--Drif 
.RE
.PP
\fBDate\fP
.RS 4
Septembre 2020 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBaudioengine\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
