.TH "/home/Theo/Téléchargements/sae/sprites/button.h" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/sprites/button.h
.SH SYNOPSIS
.br
.PP
\fC#include 'mingl/shape/rectangle\&.h'\fP
.br
\fC#include 'mingl/shape/circle\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBButton\fP (\fBMinGL\fP &window, int pos1_x, int pos1_y, int pos2_x, int pos2_y, int round, \fBnsGraphics::RGBAcolor\fP color)"
.br
.RI "cette fonction dessine un bouton avec des coins arrondis "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Button (\fBMinGL\fP & window, int pos1_x, int pos1_y, int pos2_x, int pos2_y, int round, \fBnsGraphics::RGBAcolor\fP color)"

.PP
cette fonction dessine un bouton avec des coins arrondis 
.PP
\fBParameters\fP
.RS 4
\fIwindow\fP Référence à l'objet \fBMinGL\fP pour dessiner les formes\&. 
.br
\fIpos1_x\fP Position x du coin supérieur gauche du bouton\&. 
.br
\fIpos1_y\fP Position y du coin supérieur gauche du bouton\&. 
.br
\fIpos2_x\fP Position x du coin inférieur droit du bouton\&. 
.br
\fIpos2_y\fP Position y du coin inférieur droit du bouton\&. 
.br
\fIround\fP Rayon des coins arrondis du bouton\&. Si ce rayon est plus grand que la moitié de la largeur du bouton, il sera ajusté\&. 
.br
\fIcolor\fP Couleur du bouton 
.RE
.PP

.PP
Definition at line \fB28\fP of file \fBbutton\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
