.TH "/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/exception/cexception.h" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/exception/cexception.h \- Declaration de la classe CException\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <exception>\fP
.br
\fC#include '\&.\&./tools/ieditable\&.h'\fP
.br
\fC#include 'errcode\&.h'\fP
.br
\fC#include 'cexception\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBnsException::CException\fP"
.br
.RI "Classe pour créer des exceptions facilement\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBnsException\fP"
.br
.RI "Espace de nom pour la gestion d'exceptions\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declaration de la classe CException\&. 


.PP
\fBAuthors\fP
.RS 4
M\&. Laporte, D\&. Mathieu
.RE
.PP
\fBDate\fP
.RS 4
23/03/2010
.RE
.PP
\fBVersion\fP
.RS 4
V1\&.0
.PP
V1\&.1
.RE
.PP
\fBAuthor\fP
.RS 4
Alexandre Sollier
.RE
.PP
Ajout de la documentation 
.PP
Definition in file \fBcexception\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
