.TH "/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/exception/cexception.hpp" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/exception/cexception.hpp \- classe CException  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'cexception\&.h'\fP
.br

.SH "Detailed Description"
.PP 
classe CException 


.PP
\fBAuthors\fP
.RS 4
M\&. Laporte, D\&. Mathieu
.RE
.PP
\fBDate\fP
.RS 4
23/03/2010
.RE
.PP
\fBVersion\fP
.RS 4
V1\&.0
.PP
V1\&.1
.RE
.PP
\fBAuthor\fP
.RS 4
Alexandre Sollier
.RE
.PP
Documentation complétée 
.PP
Definition in file \fBcexception\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
