.TH "CMyParamV2" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMyParamV2 \- Structure contenant les paramètres de configuration du jeu\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <type\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBtokenP1\fP"
.br
.RI "la forme du joueur 1 "
.ti -1c
.RI "char \fBtokenP2\fP"
.br
.RI "la forme du joueur 1 "
.ti -1c
.RI "char \fBKey1Up\fP"
.br
.RI "la touche pour faire monter le token1 "
.ti -1c
.RI "char \fBKey1Down\fP"
.br
.RI "la touche pour faire descendre le token1 "
.ti -1c
.RI "char \fBKey1Left\fP"
.br
.RI "la touche pour faire aller à gauche le token1 "
.ti -1c
.RI "char \fBKey1Right\fP"
.br
.RI "la touche pour faire aller à droite le token1 "
.ti -1c
.RI "char \fBKey2Up\fP"
.br
.RI "la touche pour faire monter le token2 "
.ti -1c
.RI "char \fBKey2Down\fP"
.br
.RI "la touche pour faire descendre le token2 "
.ti -1c
.RI "char \fBKey2Left\fP"
.br
.RI "la touche pour faire aller à gauche le token2 "
.ti -1c
.RI "char \fBKey2Right\fP"
.br
.RI "la touche pour faire aller à droite le token2 "
.ti -1c
.RI "std::size_t \fBNbColumn\fP"
.br
.RI "le nombre de colone qu'il doit avoir dans la map "
.ti -1c
.RI "std::size_t \fBNbRow\fP"
.br
.RI "le nombre de ligne qu'il doit avoir dans la map "
.ti -1c
.RI "std::string \fBColorP1\fP"
.br
.RI "la couleur du player 1 "
.ti -1c
.RI "std::string \fBColorP2\fP"
.br
.RI "la couleur du player 2 "
.in -1c
.SH "Detailed Description"
.PP 
Structure contenant les paramètres de configuration du jeu\&. 
.PP
Definition at line \fB82\fP of file \fBtype\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string CMyParamV2::ColorP1"

.PP
la couleur du player 1 
.PP
Definition at line \fB134\fP of file \fBtype\&.h\fP\&.
.SS "std::string CMyParamV2::ColorP2"

.PP
la couleur du player 2 
.PP
Definition at line \fB138\fP of file \fBtype\&.h\fP\&.
.SS "char CMyParamV2::Key1Down"

.PP
la touche pour faire descendre le token1 
.PP
Definition at line \fB98\fP of file \fBtype\&.h\fP\&.
.SS "char CMyParamV2::Key1Left"

.PP
la touche pour faire aller à gauche le token1 
.PP
Definition at line \fB102\fP of file \fBtype\&.h\fP\&.
.SS "char CMyParamV2::Key1Right"

.PP
la touche pour faire aller à droite le token1 
.PP
Definition at line \fB106\fP of file \fBtype\&.h\fP\&.
.SS "char CMyParamV2::Key1Up"

.PP
la touche pour faire monter le token1 
.PP
Definition at line \fB94\fP of file \fBtype\&.h\fP\&.
.SS "char CMyParamV2::Key2Down"

.PP
la touche pour faire descendre le token2 
.PP
Definition at line \fB114\fP of file \fBtype\&.h\fP\&.
.SS "char CMyParamV2::Key2Left"

.PP
la touche pour faire aller à gauche le token2 
.PP
Definition at line \fB118\fP of file \fBtype\&.h\fP\&.
.SS "char CMyParamV2::Key2Right"

.PP
la touche pour faire aller à droite le token2 
.PP
Definition at line \fB122\fP of file \fBtype\&.h\fP\&.
.SS "char CMyParamV2::Key2Up"

.PP
la touche pour faire monter le token2 
.PP
Definition at line \fB110\fP of file \fBtype\&.h\fP\&.
.SS "std::size_t CMyParamV2::NbColumn"

.PP
le nombre de colone qu'il doit avoir dans la map 
.PP
Definition at line \fB126\fP of file \fBtype\&.h\fP\&.
.SS "std::size_t CMyParamV2::NbRow"

.PP
le nombre de ligne qu'il doit avoir dans la map 
.PP
Definition at line \fB130\fP of file \fBtype\&.h\fP\&.
.SS "char CMyParamV2::tokenP1"

.PP
la forme du joueur 1 
.PP
Definition at line \fB86\fP of file \fBtype\&.h\fP\&.
.SS "char CMyParamV2::tokenP2"

.PP
la forme du joueur 1 
.PP
Definition at line \fB90\fP of file \fBtype\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
