.TH "CMyParam" 3 "Fri Jan 10 2025" "SAE 1.01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMyParam
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::map< std::string, char > \fBMapParamChar\fP"
.br
.ti -1c
.RI "std::map< std::string, unsigned > \fBMapParamUnsigned\fP"
.br
.ti -1c
.RI "std::map< std::string, std::string > \fBMapParamString\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB48\fP of file \fBtype\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::map<std::string, char> CMyParam::MapParamChar"

.PP
Definition at line \fB49\fP of file \fBtype\&.h\fP\&.
.SS "std::map<std::string, std::string> CMyParam::MapParamString"

.PP
Definition at line \fB51\fP of file \fBtype\&.h\fP\&.
.SS "std::map<std::string, unsigned> CMyParam::MapParamUnsigned"

.PP
Definition at line \fB50\fP of file \fBtype\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SAE 1\&.01 from the source code\&.
