.TH "Collectible" 3 "Fri Jan 10 2025" "SAE 1.01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Collectible
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBnom\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBpoint\fP"
.br
.ti -1c
.RI "char \fBtoken\fP"
.br
.ti -1c
.RI "std::pair< size_t, size_t > \fBpos\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB148\fP of file \fBtype\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Collectible::id"

.PP
Definition at line \fB151\fP of file \fBtype\&.h\fP\&.
.SS "std::string Collectible::nom"

.PP
Definition at line \fB150\fP of file \fBtype\&.h\fP\&.
.SS "int Collectible::point"

.PP
Definition at line \fB152\fP of file \fBtype\&.h\fP\&.
.SS "std::pair<size_t,size_t> Collectible::pos"

.PP
Definition at line \fB154\fP of file \fBtype\&.h\fP\&.
.SS "char Collectible::token"

.PP
Definition at line \fB153\fP of file \fBtype\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SAE 1\&.01 from the source code\&.
