.TH "/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/exception/errcode.h" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/exception/errcode.h \- Codes d'erreurs\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBnsException\fP"
.br
.RI "Espace de nom pour la gestion d'exceptions\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBnsException::KNoExc\fP = 0, \fBnsException::KNoError\fP = 0, \fBnsException::kColorOutOfBounds\fP = 100, \fBnsException::KFileError\fP = 252, \fBnsException::KErrArg\fP = 253, \fBnsException::KExcStd\fP = 254, \fBnsException::kExcInconnue\fP = -1, \fBnsException::kErrTooHight\fP = 300, \fBnsException::kErrTooRight\fP = 301, \fBnsException::kErrFontSize\fP = 302, \fBnsException::kNoTriangle\fP = 303, \fBnsException::kNoLine\fP = 304, \fBnsException::kNoRectangle\fP = 305, \fBnsException::kNoCircle\fP = 306, \fBnsException::kTypeNotFound\fP = 307 }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::map< unsigned, std::string > \fBnsException::kError\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Codes d'erreurs\&. 


.PP
\fBAuthors\fP
.RS 4
D\&. Mathieu
.RE
.PP
\fBDate\fP
.RS 4
28/08/2010
.RE
.PP
\fBVersion\fP
.RS 4
V2\&.0
.PP
V2\&.1
.RE
.PP
\fBAuthor\fP
.RS 4
Alexandre Sollier
.RE
.PP
Ajout de la documentation, renommage du fichier 
.PP
Definition in file \fBerrcode\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
