.TH "/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/event/event_manager.h" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/event/event_manager.h \- Gestionnaire d'événements de minGL\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <queue>\fP
.br
\fC#include 'event\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBnsEvent::EventManager\fP"
.br
.RI "Gère une queue d'événement entrants\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBnsEvent\fP"
.br
.RI "Espace de nom pour la gestion d'événements\&. "
.in -1c
.SH "Detailed Description"
.PP 
Gestionnaire d'événements de minGL\&. 


.PP
\fBAuthor\fP
.RS 4
Alexandre Sollier 
.RE
.PP
\fBDate\fP
.RS 4
Décembre 2019 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBevent_manager\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
