.TH "Form" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Form
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <type\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBnom\fP"
.br
.ti -1c
.RI "std::pair< size_t, size_t > \fBdim\fP"
.br
.ti -1c
.RI "std::vector< std::vector< char > > \fBpiece\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB141\fP of file \fBtype\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::pair<size_t,size_t> Form::dim"

.PP
Definition at line \fB144\fP of file \fBtype\&.h\fP\&.
.SS "std::string Form::nom"

.PP
Definition at line \fB143\fP of file \fBtype\&.h\fP\&.
.SS "std::vector< std::vector<char> > Form::piece"

.PP
Definition at line \fB145\fP of file \fBtype\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
