.TH "/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/gui/glut_font.h" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/gui/glut_font.h \- Classe utilitaire pour utiliser facilement les polices de Glut\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBnsGui::GlutFont\fP"
.br
.RI "Classe listant toute les polices rendues disponibles par Glut, a utiliser avec \fBText\fP\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBnsGui\fP"
.br
.RI "Espace de nom pour des éléments d'interface complexes\&. "
.in -1c
.SH "Detailed Description"
.PP 
Classe utilitaire pour utiliser facilement les polices de Glut\&. 


.PP
\fBAuthor\fP
.RS 4
Alexandre Sollier 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.1 
.RE
.PP
\fBDate\fP
.RS 4
28 décembre 2019 
.RE
.PP

.PP
Definition in file \fBglut_font\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
