.TH "/home/Theo/Téléchargements/sae/Jeu/gridmanagement.cpp" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/Jeu/gridmanagement.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'gridmanagement\&.h'\fP
.br
\fC#include 'type\&.h'\fP
.br
\fC#include <bits/stdc++\&.h>\fP
.br
\fC#include <cmath>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBajouterpiece\fP (\fBCMat\fP &Mat, const \fBForm\fP &forme, int x, int y)"
.br
.ti -1c
.RI "void \fBrotation90\fP (\fBForm\fP &forme)"
.br
.ti -1c
.RI "void \fBClearScreen\fP ()"
.br
.RI "Clear the current terminal\&. "
.ti -1c
.RI "void \fBColor\fP (const string &Col)"
.br
.ti -1c
.RI "void \fBDisplayGrid\fP (const \fBCMat\fP &Mat, const \fBCMyParamV2\fP &Param)"
.br
.ti -1c
.RI "void \fBInitGrid\fP (\fBCMat\fP &Mat, unsigned NbLine, unsigned NbColumn, \fBCPosition\fP &PosPlayer1, \fBCPosition\fP &PosPlayer2, const \fBCMyParamV2\fP &Param, \fBCPosition\fP &Tp1, \fBCPosition\fP &Tp2, vector< \fBCPosition\fP > &PosMonster)"
.br
.ti -1c
.RI "void \fBMoveMonster\fP (vector< \fBCPosition\fP > &VPosMonster, \fBCMat\fP &Mat, const \fBCMyParamV2\fP &param, const \fBCPosition\fP &PosPlayer1, const \fBCPosition\fP &PosPlayer2)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ajouterpiece (\fBCMat\fP & Mat, const \fBForm\fP & forme, int x, int y)"

.PP
Definition at line \fB75\fP of file \fBgridmanagement\&.cpp\fP\&.
.SS "void ClearScreen ()"

.PP
Clear the current terminal\&. 
.PP
Definition at line \fB113\fP of file \fBgridmanagement\&.cpp\fP\&.
.SS "void Color (const string & Col)"

.PP
Definition at line \fB117\fP of file \fBgridmanagement\&.cpp\fP\&.
.SS "void DisplayGrid (const \fBCMat\fP & Mat, const \fBCMyParamV2\fP & Param)"

.PP
Definition at line \fB122\fP of file \fBgridmanagement\&.cpp\fP\&.
.SS "void InitGrid (\fBCMat\fP & Mat, unsigned NbLine, unsigned NbColumn, \fBCPosition\fP & PosPlayer1, \fBCPosition\fP & PosPlayer2, const \fBCMyParamV2\fP & Param, \fBCPosition\fP & Tp1, \fBCPosition\fP & Tp2, vector< \fBCPosition\fP > & PosMonster)"

.PP
Definition at line \fB165\fP of file \fBgridmanagement\&.cpp\fP\&.
.SS "void MoveMonster (vector< \fBCPosition\fP > & VPosMonster, \fBCMat\fP & Mat, const \fBCMyParamV2\fP & param, const \fBCPosition\fP & PosPlayer1, const \fBCPosition\fP & PosPlayer2)"

.PP
Definition at line \fB341\fP of file \fBgridmanagement\&.cpp\fP\&.
.SS "void rotation90 (\fBForm\fP & forme)"

.PP
Definition at line \fB97\fP of file \fBgridmanagement\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
