.TH "/home/Theo/Téléchargements/sae/SAE_JEU/MinGL2_IUT_AIX-master/include/mingl/tools/ieditable.h" 3 "Fri Jan 10 2025" "SAE 1.01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/SAE_JEU/MinGL2_IUT_AIX-master/include/mingl/tools/ieditable.h \- declaration de la classe CEditable dans \fBnsUtil\fP  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'ieditable\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBnsUtil::IEditable\fP"
.br
.RI "Interface pour un objet injectable\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBnsUtil\fP"
.br
.RI "Espace de nom pour les utilitaires lambda\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBnsUtil::operator<<\fP (std::ostream &os, const IEditable &Obj)"
.br
.in -1c
.SH "Detailed Description"
.PP 
declaration de la classe CEditable dans \fBnsUtil\fP 


.PP
\fBAuthors\fP
.RS 4
D\&. Mathieu, M\&. Laporte
.RE
.PP
\fBDate\fP
.RS 4
16/03/2009
.RE
.PP
\fBVersion\fP
.RS 4
V2\&.0
.PP
V2\&.1
.RE
.PP
\fBAuthor\fP
.RS 4
Alexandre Sollier
.RE
.PP
Ajout de la documentation 
.PP
Definition in file \fBieditable\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SAE 1\&.01 from the source code\&.
