.TH "/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/tools/ifonctorunaire.hpp" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/tools/ifonctorunaire.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBnsUtil::IFonctorUnaire< T1, TRes >\fP"
.br
.RI "Interface pour un fonctor unaire\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBnsUtil\fP"
.br
.RI "Espace de nom pour les utilitaires lambda\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
