.TH "img2si" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
img2si
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBis_file_si2\fP (filePath)"
.br
.ti -1c
.RI "def \fBconvert_from_si2\fP (source, output)"
.br
.ti -1c
.RI "def \fBconvert_to_si2\fP (source, output)"
.br
.ti -1c
.RI "def \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def img2si\&.convert_from_si2 ( source,  output)"

.PP
Definition at line \fB34\fP of file \fBimg2si\&.py\fP\&.
.SS "def img2si\&.convert_to_si2 ( source,  output)"

.PP
Definition at line \fB59\fP of file \fBimg2si\&.py\fP\&.
.SS "def img2si\&.is_file_si2 ( filePath)"

.PP
Definition at line \fB28\fP of file \fBimg2si\&.py\fP\&.
.SS "def img2si\&.main ()"

.PP
Definition at line \fB95\fP of file \fBimg2si\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
