.TH "/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/tools/img2si.py" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/tools/img2si.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBimg2si\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBimg2si\&.is_file_si2\fP (filePath)"
.br
.ti -1c
.RI "def \fBimg2si\&.convert_from_si2\fP (source, output)"
.br
.ti -1c
.RI "def \fBimg2si\&.convert_to_si2\fP (source, output)"
.br
.ti -1c
.RI "def \fBimg2si\&.main\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
