.TH "/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/transition/itransitionable.h" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/transition/itransitionable.h \- Interface pour objet 'transitionable'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBnsTransition::ITransitionable\fP"
.br
.RI "Une classe abstraite pour n'importe quelle élément pouvant effectuer une transition entre deux états\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBnsTransition\fP"
.br
.RI "Espace de nom pour le moteur de transition et ses composants\&. "
.in -1c
.SH "Detailed Description"
.PP 
Interface pour objet 'transitionable'\&. 


.PP
\fBAuthor\fP
.RS 4
Alexandre Sollier 
.RE
.PP
\fBDate\fP
.RS 4
Janvier 2020 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBitransitionable\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
