.TH "/home/Theo/Téléchargements/sae/sprites/kebab.h" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/sprites/kebab.h
.SH SYNOPSIS
.br
.PP
\fC#include 'mingl/shape/rectangle\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBKebab\fP (\fBMinGL\fP &window, int Pos1, int Pos2, int mat_x, int mat_y)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Kebab (\fBMinGL\fP & window, int Pos1, int Pos2, int mat_x, int mat_y)"

.PP
Definition at line \fB15\fP of file \fBkebab\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
