.TH "md__home__theo__t_xC3_xA9l_xC3_xA9chargements_sae__min_g_l2__i_u_t__a_i_x_master_tools__r_e_a_d_m_e" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home__theo__t_xC3_xA9l_xC3_xA9chargements_sae__min_g_l2__i_u_t__a_i_x_master_tools__r_e_a_d_m_e \- Outils minGL 2 
Ce répertoire contient des outils relatif a certaines fonctionnalitées minGL 2\&.
.SH "Script de conversion \&.si2"
.PP
\fBMinGL\fP 2 supporte le chargement d'images sous le format \fC\&.si2\fP, qui est un format d'image non-compressé, type bitmap avec support de la transparence\&. 
.br
 Un script Python 3 permettant de transformer n'importe quelle image en \fC\&.si2\fP (et inversement) vous est fourni ici, nommé \fC\fBimg2si\&.py\fP\fP\&.
.PP
Le spécifications de ce format de fichier vous sont écrites dans ce même script Python, en commentaire\&.
.PP
Ce script Python est dépendant de la biliothèque Pillow, que vous pouvez installer via pip: 
.PP
.nf
python3 -m pip install --upgrade pip
python3 -m pip install --upgrade Pillow

.fi
.PP
 
