.TH "md__home__theo__t_xC3_xA9l_xC3_xA9chargements_sae__s_a_e__j_e_u__min_g_l2__i_u_t__a_i_x_master__r_e_a_d_m_e" 3 "Fri Jan 10 2025" "SAE 1.01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home__theo__t_xC3_xA9l_xC3_xA9chargements_sae__s_a_e__j_e_u__min_g_l2__i_u_t__a_i_x_master__r_e_a_d_m_e \- minGL 2 
\fBMinGL\fP 2 est un bibliothèque écrite en C++, évolution de \fBMinGL\fP par Alain Casali, enseignant chercheur au département informatique de l'IUT d'Aix-en-Provence\&. 
.br
 Elle facilite l'affichage de forme primitives et composées, de texte et la réalisation d'animations\&. Elle permet également de jouer des fichiers audios et de gérer les saisies clavier et souris\&.
.PP
Développé dans un but pédagogique\&.
.SH "Installation"
.PP
Les dépendances suivantes sont requises pour utiliser minGL 2:
.IP "\(bu" 2
freeglut
.IP "\(bu" 2
sfml (audio)
.PP
.PP
Installation sous \fBDebian et dérivés\fP: 
.PP
.nf
sudo apt-get install freeglut3-dev libsfml-dev

.fi
.PP
.PP
Installation sous \fBArch Linux et Manjaro\fP:  
.PP
.nf
sudo pacman -S freeglut sfml

.fi
.PP
.PP
Installation sous \fBmacOS\fP (avec \fCHomebrew\fP préalablement installé): 
.PP
.nf
brew cask install xquartz
brew install freeglut sfml

.fi
.PP
 \fBImportant\fP: Afin de terminer l'installation de XQuartz, macOS doit être redémarré\&.
.PP
Testé sous Debian 10, Ubuntu 20\&.04, macOS 10\&.15, Manjaro GNU/Linux (audio non testé)
.SH "Utilisation"
.PP
.SS "Avec un autre projet qmake"
Pour utiliser minGL 2 dans votre projet qmake, il vous suffit de décompresser (ou encore mieux, mettre en sous-module git) cette bibliothèque dans un sous-répertoire du répertoire contenant votre fichier \fC\&.pro\fP\&. 
.br
 Il vous suffit ensuite de rajouter dans votre \fC\&.pro\fP la directive \fCinclude(\&.\&.\&./mingl\&.pri)\fP, en remplaçant \fC\&.\&.\&.\fP par le chemin du répertoire de minGL 2\&.
.PP
Par exemple, si vous avez décompressé minGL 2 dans le sous-répertoire \fCminGL2/\fP présent dans le même répertoire que votre \fC\&.pro\fP, alors vous devez écrire dans ce dernier: \fCinclude(minGL2/mingl\&.pri)\fP\&.
.SS "En tant que bibliothèque"
Vous pouvez facilement compiler minGL 2 en tant que bibliothèque afin de générer le fichier \fClibmingl\&.a\fP\&. 
.br
 Il vous suffit simplement d'ouvrir le fichier de projet \fCmingl\&.pro\fP et de lancer la compilation, vous trouverez le fichier \fC\&.a\fP dans le répertoire de compilation\&. 
.br
 Le répertoire \fCinclude/\fP contient tout les fichiers d'en-tête de minGL 2\&.
.SS "Extras"
Si vous avez \fCdoxygen\fP installé sur votre machine, vous pouvez générer, dans le répertoire \fCdoc/\fP, une documentation HTML de minGL 2 avec la commande suivante: 
.PP
.nf
doxygen Doxyfile

.fi
.PP
.PP
Dans le répertoire \fCtools/\fP, vous trouverez des outils relatif a l'utilisation de minGL 2\&.
.SH "Remerciements"
.PP
.IP "\(bu" 2
\fBAlexandre Sollier et Clément Mathieu--Drif\fP: Développeurs principaux de minGL 2
.IP "\(bu" 2
\fBAlain Casali\fP: Auteur de la version originale de \fBMinGL\fP
.IP "\(bu" 2
La promo 2020-2021 de la 2ème année du Département Informatique de l'IUT d'Aix-en-Provence 
.PP

