.TH "/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/mingl.h" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/mingl.h \- La bête\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <queue>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <GL/freeglut\&.h>\fP
.br
\fC#include 'graphics/idrawable\&.h'\fP
.br
\fC#include 'graphics/rgbacolor\&.h'\fP
.br
\fC#include 'graphics/vec2d\&.h'\fP
.br
\fC#include 'event/event_manager\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMinGL\fP"
.br
.RI "Classe de base de minGL 2\&. "
.in -1c
.SH "Detailed Description"
.PP 
La bête\&. 


.PP
\fBAuthor\fP
.RS 4
Alexandre Sollier, Clément Mathieu--Drif, Alain Casali 
.RE
.PP
\fBDate\fP
.RS 4
Janvier 2020 
.RE
.PP
\fBVersion\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition in file \fBmingl\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
