.TH "Node" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Node \- Structure représentant un noeud dans un graphe dans Movemonster() struct représentant un noeud dans un graphe, avec pos sa position, f_cost un coût estimé et son parent\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <type\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCPosition\fP \fBPos\fP"
.br
.ti -1c
.RI "size_t \fBf_cost\fP"
.br
.ti -1c
.RI "\fBCPosition\fP \fBParent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure représentant un noeud dans un graphe dans Movemonster() struct représentant un noeud dans un graphe, avec pos sa position, f_cost un coût estimé et son parent\&. 
.PP
Definition at line \fB170\fP of file \fBtype\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "size_t Node::f_cost"

.PP
Definition at line \fB172\fP of file \fBtype\&.h\fP\&.
.SS "\fBCPosition\fP Node::Parent"

.PP
Definition at line \fB173\fP of file \fBtype\&.h\fP\&.
.SS "\fBCPosition\fP Node::Pos"

.PP
Definition at line \fB171\fP of file \fBtype\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
