.TH "nsAudio" 3 "Fri Jan 10 2025" "SAE 1.01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nsAudio \- Espace de nom pour les utilitaires audio\&. Il est conseillé d'utiliser des fichiers \&.wav\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAudioEngine\fP"
.br
.RI "Une classe de gestion des effets audio et de la musique\&. "
.in -1c
.SH "Detailed Description"
.PP 
Espace de nom pour les utilitaires audio\&. Il est conseillé d'utiliser des fichiers \&.wav\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for SAE 1\&.01 from the source code\&.
