.TH "nsEvent::Event_t" 3 "Fri Jan 10 2025" "SAE 1.01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nsEvent::Event_t \- Possède des données pour un événement\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <event\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEventType_t\fP \fBeventType\fP"
.br
.ti -1c
.RI "\fBEventData_t\fP \fBeventData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Possède des données pour un événement\&. 
.PP
Definition at line \fB62\fP of file \fBevent\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBEventData_t\fP nsEvent::Event_t::eventData"
Données de l'événement 
.PP
Definition at line \fB64\fP of file \fBevent\&.hpp\fP\&.
.SS "\fBEventType_t\fP nsEvent::Event_t::eventType"
Type de l'événement 
.PP
Definition at line \fB63\fP of file \fBevent\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SAE 1\&.01 from the source code\&.
