.TH "nsEvent::EventData_t" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nsEvent::EventData_t \- Union contenant les données d'un événement\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <event\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMouseClickData_t\fP \fBclickData\fP"
.br
.ti -1c
.RI "\fBMouseMoveData_t\fP \fBmoveData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Union contenant les données d'un événement\&. 
.PP
Definition at line \fB53\fP of file \fBevent\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBMouseClickData_t\fP nsEvent::EventData_t::clickData"
Données pour un événement MouseClick 
.PP
Definition at line \fB54\fP of file \fBevent\&.hpp\fP\&.
.SS "\fBMouseMoveData_t\fP nsEvent::EventData_t::moveData"
Données pour un événment MouseMove/MouseDrag 
.PP
Definition at line \fB55\fP of file \fBevent\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
