.TH "nsEvent::MouseMoveData_t" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nsEvent::MouseMoveData_t \- Possède des données pour un événement MouseMove/MouseDrag\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <event\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Possède des données pour un événement MouseMove/MouseDrag\&. 
.PP
Definition at line \fB44\fP of file \fBevent\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int nsEvent::MouseMoveData_t::x"
Coordonnée X du curseur, relative au coin supérieur-gauche de la fenêtre 
.PP
Definition at line \fB45\fP of file \fBevent\&.hpp\fP\&.
.SS "int nsEvent::MouseMoveData_t::y"
Coordonnée Y du curseur, relative au coin supérieur-gauche de la fenêtre 
.PP
Definition at line \fB46\fP of file \fBevent\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
