.TH "nsGui" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nsGui \- Espace de nom pour des éléments d'interface complexes\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGlutFont\fP"
.br
.RI "Classe listant toute les polices rendues disponibles par Glut, a utiliser avec \fBText\fP\&. "
.ti -1c
.RI "class \fBSprite\fP"
.br
.RI "Permet de charger une image depuis un format créé pour l'occasion, le \&.si2\&. "
.ti -1c
.RI "class \fBText\fP"
.br
.RI "Gère l'affichage d'un texte\&. "
.in -1c
.SH "Detailed Description"
.PP 
Espace de nom pour des éléments d'interface complexes\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
