.TH "nsUtil" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nsUtil \- Espace de nom pour les utilitaires lambda\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIEditable\fP"
.br
.RI "Interface pour un objet injectable\&. "
.ti -1c
.RI "class \fBIFonctorUnaire\fP"
.br
.RI "Interface pour un fonctor unaire\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBIEditable\fP &Obj)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Espace de nom pour les utilitaires lambda\&. 
.SH "Function Documentation"
.PP 
.SS "std::ostream & nsUtil::operator<< (std::ostream & os, const \fBIEditable\fP & Obj)\fC [inline]\fP"

.PP
Definition at line \fB20\fP of file \fBieditable\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
