.TH "/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/src/shape/oval.cpp" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/src/shape/oval.cpp \- Représente un oval\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include 'mingl/shape/oval\&.h'\fP
.br
\fC#include 'mingl/macros\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Représente un oval\&. 


.PP
\fBAuthor\fP
.RS 4
Matisse QUILLIEC 
.RE
.PP
\fBDate\fP
.RS 4
December 2024 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBoval\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
