.TH "/home/Theo/Téléchargements/sae/Jeu/params.cpp" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/Jeu/params.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'params\&.h'\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitParams\fP (\fBCMyParamV2\fP &Param)"
.br
.ti -1c
.RI "void \fBLoadParams\fP (\fBCMyParamV2\fP &Param)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void initParams (\fBCMyParamV2\fP & Param)"

.PP
Definition at line \fB9\fP of file \fBparams\&.cpp\fP\&.
.SS "void LoadParams (\fBCMyParamV2\fP & Param)"

.PP
Definition at line \fB32\fP of file \fBparams\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
