.TH "/home/Theo/Téléchargements/sae/Jeu/params.h" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/Jeu/params.h \- Paramters' definition and associated functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'type\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitParams\fP (\fBCMyParamV2\fP &param)"
.br
.ti -1c
.RI "void \fBinitParamsV2\fP (\fBCMyParamV2\fP &param)"
.br
.ti -1c
.RI "void \fBLoadParams\fP (\fBCMyParamV2\fP &Param)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Paramters' definition and associated functions\&. 


.PP
\fBAuthor\fP
.RS 4
Alain Casali 
.PP
Marc Laporte 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
18 décembre 2018 
.RE
.PP

.PP
Definition in file \fBparams\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void initParams (\fBCMyParamV2\fP & param)"

.PP
Definition at line \fB9\fP of file \fBparams\&.cpp\fP\&.
.SS "void initParamsV2 (\fBCMyParamV2\fP & param)"

.SS "void LoadParams (\fBCMyParamV2\fP & Param)"

.PP
Definition at line \fB32\fP of file \fBparams\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
