.TH "/home/Theo/Téléchargements/sae/SAE_JEU/sprites/player2.h" 3 "Fri Jan 10 2025" "SAE 1.01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/SAE_JEU/sprites/player2.h \- Affiche le sprite du player 2\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mingl/shape/circle\&.h'\fP
.br
\fC#include 'mingl/shape/oval\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPlayer2\fP (\fBMinGL\fP &window, int Circle1, int Circle2, int mat_x, int mat_y)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Affiche le sprite du player 2\&. 


.PP
\fBAuthor\fP
.RS 4
Matisse Quilliec 
.RE
.PP
\fBDate\fP
.RS 4
December 2024 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBplayer2\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void Player2 (\fBMinGL\fP & window, int Circle1, int Circle2, int mat_x, int mat_y)"

.PP
Definition at line \fB16\fP of file \fBplayer2\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SAE 1\&.01 from the source code\&.
