.TH "/home/Theo/Téléchargements/sae/sprites/player1.h" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/sprites/player1.h \- Affiche le sprite du player 1\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mingl/shape/circle\&.h'\fP
.br
\fC#include 'mingl/shape/oval\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPlayer1\fP (\fBMinGL\fP &window, int Circle1, int Circle2, int mat_x, int mat_y)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Affiche le sprite du player 1\&. 


.PP
\fBAuthor\fP
.RS 4
Matisse Quilliec 
.RE
.PP
\fBDate\fP
.RS 4
December 2024 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBplayer1\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void Player1 (\fBMinGL\fP & window, int Circle1, int Circle2, int mat_x, int mat_y)"

.PP
Definition at line \fB16\fP of file \fBplayer1\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
