.TH "/home/Theo/Téléchargements/sae/sprites/teleporter.h" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/sprites/teleporter.h
.SH SYNOPSIS
.br
.PP
\fC#include 'mingl/shape/rectangle\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTeleporter\fP (\fBMinGL\fP &window, int Pos1, int Pos2, int mat_x, int mat_y)"
.br
.RI "cette fonction dessine un teleporter soit l'ascenceur "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Teleporter (\fBMinGL\fP & window, int Pos1, int Pos2, int mat_x, int mat_y)"

.PP
cette fonction dessine un teleporter soit l'ascenceur 
.PP
\fBParameters\fP
.RS 4
\fIwindow\fP Référence à l'objet \fBMinGL\fP pour dessiner les formes\&. 
.br
\fIPos1\fP Position x du centre du téléporteur\&. 
.br
\fIPos2\fP Position y du centre du téléporteur\&. 
.br
\fImat_x\fP Facteur d'échelle pour la dimension horizontale des éléments du téléporteur\&. 
.br
\fImat_y\fP Facteur d'échelle pour la dimension verticale des éléments du téléporteur\&. 
.RE
.PP

.PP
Definition at line \fB26\fP of file \fBteleporter\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
