.TH "/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/src/gui/text.cpp" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/src/gui/text.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mingl/gui/text\&.h'\fP
.br
\fC#include 'mingl/macros\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
