.TH "/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/gui/text.h" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/gui/text.h \- Du texte\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'glut_font\&.h'\fP
.br
\fC#include '\&.\&./graphics/idrawable\&.h'\fP
.br
\fC#include '\&.\&./graphics/rgbacolor\&.h'\fP
.br
\fC#include '\&.\&./graphics/vec2d\&.h'\fP
.br
\fC#include '\&.\&./transition/itransitionable\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBnsGui::Text\fP"
.br
.RI "Gère l'affichage d'un texte\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBnsGui\fP"
.br
.RI "Espace de nom pour des éléments d'interface complexes\&. "
.in -1c
.SH "Detailed Description"
.PP 
Du texte\&. 


.PP
\fBAuthor\fP
.RS 4
Alexandre Sollier 
.RE
.PP
\fBDate\fP
.RS 4
Janvier 2020 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBtext\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
