.TH "/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/transition/transition_contract.h" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/transition/transition_contract.h \- Création de la transition\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <functional>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'itransitionable\&.h'\fP
.br
\fC#include 'transition_types\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBnsTransition::TransitionContract\fP"
.br
.RI "Une classe contenant des paramètres pour créer une transition\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBnsTransition\fP"
.br
.RI "Espace de nom pour le moteur de transition et ses composants\&. "
.in -1c
.SH "Detailed Description"
.PP 
Création de la transition\&. 


.PP
\fBAuthor\fP
.RS 4
Alexandre Sollier 
.RE
.PP
\fBDate\fP
.RS 4
Janvier 2020 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBtransition_contract\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
