.TH "/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/shape/triangle.h" 3 "Sun Jan 12 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/MinGL2_IUT_AIX-master/include/mingl/shape/triangle.h \- Représente un triangle\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'shape\&.h'\fP
.br
\fC#include '\&.\&./transition/itransitionable\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBnsShape::Triangle\fP"
.br
.RI "Classe représentant un triangle\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBnsShape\fP"
.br
.RI "Espace de nom pour différentes formes\&. "
.in -1c
.SH "Detailed Description"
.PP 
Représente un triangle\&. 


.PP
\fBAuthor\fP
.RS 4
Alexandre Sollier 
.RE
.PP
\fBDate\fP
.RS 4
Janvier 2020 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBtriangle\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
