.TH "/home/Theo/Téléchargements/sae/SAE_JEU/MinGL2_IUT_AIX-master/src/graphics/vec2d.cpp" 3 "Fri Jan 10 2025" "SAE 1.01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Theo/Téléchargements/sae/SAE_JEU/MinGL2_IUT_AIX-master/src/graphics/vec2d.cpp \- Représente un vecteur sur deux dimensions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include 'mingl/graphics/vec2d\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Représente un vecteur sur deux dimensions\&. 


.PP
\fBAuthor\fP
.RS 4
Alexandre Sollier 
.RE
.PP
\fBDate\fP
.RS 4
Septembre 2020 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.3 
.RE
.PP

.PP
Definition in file \fBvec2d\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SAE 1\&.01 from the source code\&.
