MenuManagement.h
nsGraphics::Vec2D rectPos
Referenced by events.
nsGraphics::RGBAcolor rectColor
Referenced by events.
void InterfaceMenuP(MinGL &window, int mat_x, int mat_y)
References nsGui::GlutFont::BITMAP_TIMES_ROMAN_24, Button, nsGraphics::KBlack, nsGraphics::KGray, nsGraphics::KWhite.
Referenced by MenuP.
void InterfacePause(MinGL &window, int mat_x, int mat_y)
References nsGraphics::KBlue, nsGraphics::KGray.
Referenced by Pause.
void InterfaceOptions(MinGL &window, int mat_x, int mat_y)
References nsGui::GlutFont::BITMAP_HELVETICA_12, nsGraphics::KGray, nsGraphics::KRed, nsGraphics::KTransparent, nsGraphics::KWhite.
Referenced by Options.
void InterfaceCredits(MinGL &window, int mat_x, int mat_y)
References nsGui::GlutFont::BITMAP_TIMES_ROMAN_24, nsGraphics::KGray, nsGraphics::KTransparent, nsGraphics::KWhite.
Referenced by Credits.
void events(MinGL &window, vector< tuple< vector< int >, vector< int >, int > > &clickablepool, int &menuid)
Handle user input events such as mouse movement and clicks for menu navigation.
window : Mingl window clickablepool : list of clickable areas with their coordinates and associated menu ID [in/out] menuid : current menu ID, which is updated based on user clicks
References nsEvent::EventData_t::clickData, nsEvent::Event_t::eventData, nsEvent::Event_t::eventType, MinGL::getEventManager, nsGraphics::Vec2D::getX, nsGraphics::Vec2D::getY, nsEvent::EventManager::hasEvent, nsGraphics::KPurple, nsEvent::MouseClick, nsEvent::MouseMove, nsEvent::EventData_t::moveData, nsEvent::EventManager::pullEvent, rectColor, rectPos, nsGraphics::Vec2D::setX, nsGraphics::Vec2D::setY, nsEvent::MouseClickData_t::state, nsEvent::MouseMoveData_t::x, nsEvent::MouseMoveData_t::y.