main.cpp
FPS_LIMIT
nsGraphics::Vec2D rectPos
Referenced by clavier, dessiner, events.
nsGraphics::RGBAcolor rectColor
Referenced by dessiner, events.
void events(MinGL &window)
References nsEvent::EventData_t::clickData, nsEvent::Event_t::eventData, nsEvent::Event_t::eventType, MinGL::getEventManager, nsEvent::EventManager::hasEvent, nsGraphics::KCyan, nsGraphics::KPurple, nsEvent::MouseClick, nsEvent::MouseMove, nsEvent::EventData_t::moveData, nsEvent::EventManager::pullEvent, rectColor, rectPos, nsGraphics::Vec2D::setX, nsGraphics::Vec2D::setY, nsEvent::MouseClickData_t::state, nsEvent::MouseMoveData_t::x, nsEvent::MouseMoveData_t::y.
Referenced by Credits, GameLoop, main, MenuP, Options, Pause.
void dessiner(MinGL &window)
References rectColor, rectPos.
Referenced by main.
int main()
References MinGL::clearScreen, dessiner, events, MinGL::finishFrame, FPS_LIMIT, MinGL::initGlut, MinGL::initGraphic, MinGL::isOpen, nsGraphics::KBlack.