nsGraphics::Vec2D
int nsGraphics::Vec2D::m_x
m_x : Position X (abscisse)
int nsGraphics::Vec2D::m_y
m_y : Position Y (ordonnée)
nsGraphics::Vec2D::Vec2D(const int &x=0, const int &y=0)
Constructeur pour la classe Vec2D.
x : Position X (abscisse) du vecteur y : Position Y (ordonnée) du vecteur
nsGraphics::Vec2D::Vec2D(const Vec2D &pos)
Constructeur de recopie pour la classe Vec2D.
pos : Vec2D a copier
Vec2D nsGraphics::Vec2D::operator+() const
Opérateur unaire plus.
Vec2D nsGraphics::Vec2D::operator-() const
Opérateur unaire moins.
Vec2D nsGraphics::Vec2D::operator+(const Vec2D &pos) const
Opérateur d'addition.
pos : Vecteur a additionner
References getX, getY.
Vec2D nsGraphics::Vec2D::operator-(const Vec2D &pos) const
Opérateur de soustraction.
pos : Vecteur a soustraire
References getX, getY.
Vec2D nsGraphics::Vec2D::operator*(const Vec2D &pos) const
Opérateur de multiplication.
pos : Vecteur a multiplier
References getX, getY.
Vec2D nsGraphics::Vec2D::operator*(const float &n) const
Opérateur de multiplication.
n : Nombre avec lequel multiplier le vecteur actuel
Vec2D nsGraphics::Vec2D::operator/(const Vec2D &pos) const
Opérateur de division.
pos : Vecteur a diviser
References getX, getY.
Vec2D nsGraphics::Vec2D::operator/(const float &n) const
Opérateur de division.
n : Nombre avec lequel diviser le vecteur actuel
Vec2D nsGraphics::Vec2D::operator%(const Vec2D &pos) const
Opérateur modulo.
pos : Vecteur avec lequel faire un modulo
References getX, getY.
bool nsGraphics::Vec2D::operator==(const Vec2D &pos) const
Opérateur d'égalité
pos : Vecteur avec lequel vérifier l'égalité
References getX, getY.
bool nsGraphics::Vec2D::operator!=(const Vec2D &pos) const
Opérateur d'inégalité
pos : Vecteur avec lequel vérifier l'inégalité
References getX, getY.
bool nsGraphics::Vec2D::operator<(const Vec2D &pos) const
Opérateur de stricte infériorité (Vérifie la stricte infériorité de la magnitude des deux vecteurs)
pos : Vecteur avec lequel vérifier la stricte infériorité
References computeMagnitude.
bool nsGraphics::Vec2D::operator>(const Vec2D &pos) const
Opérateur de stricte supériorité (Vérifie la stricte supériorité de la magnitude des deux vecteurs)
pos : Vecteur avec lequel vérifier la stricte supériorité
References computeMagnitude.
bool nsGraphics::Vec2D::operator<=(const Vec2D &pos) const
Opérateur d'infériorité (Vérifie l'infériorité de la magnitude des deux vecteurs)
pos : Vecteur avec lequel vérifier l'infériorité
References computeMagnitude.
bool nsGraphics::Vec2D::operator>=(const Vec2D &pos) const
Opérateur de supériorité (Vérifie la supériorité de la magnitude des deux vecteurs)
pos : Vecteur avec lequel vérifier la supériorité
References computeMagnitude.
Vec2D & nsGraphics::Vec2D::operator=(const Vec2D &pos)
Opérateur d'assignement.
pos : Vecteur source
References getX, getY.
Vec2D & nsGraphics::Vec2D::operator+=(const Vec2D &pos)
Opérateur d'addition avec assignement.
pos : Vecteur avec lequel additionner le vecteur actuel
References getX, getY.
Vec2D & nsGraphics::Vec2D::operator-=(const Vec2D &pos)
Opérateur de soustraction avec assignement.
pos : Vecteur avec lequel soustraire le vecteur actuel
References getX, getY.
Vec2D & nsGraphics::Vec2D::operator*=(const Vec2D &pos)
Opérateur de multiplication avec assignement.
pos : Vecteur avec lequel multiplier le vecteur actuel
References getX, getY.
Vec2D & nsGraphics::Vec2D::operator/=(const Vec2D &pos)
Opérateur de division avec assignement.
pos : Vecteur avec lequel diviser le vecteur actuel
References getX, getY.
Vec2D & nsGraphics::Vec2D::operator%=(const Vec2D &pos)
Opérateur modulo avec assignement.
pos : Vecteur avec lequel faire un modulo sur le vecteur actuel
References getX, getY.
bool nsGraphics::Vec2D::isColliding(Vec2D firstCorner, Vec2D secondCorner) const
Retourne vrai si le vecteur actuel est compris entre deux vecteurs formant un rectangle.
firstCorner : Premier vecteur secondCorner : Second vecteur
References getX, getY.
double nsGraphics::Vec2D::computeMagnitude() const
Calcule la magnitude de ce vecteur.
Magnitude du vecteur
Referenced by operator<, operator<=, operator>, operator>=.
int nsGraphics::Vec2D::getX() const
Récupère la position X (abscisse)
Une référence constante vers m_x
Referenced by clavier, nsGui::Text::computeVisiblePosition, nsGui::Text::draw, events, isColliding, min, MinGL::MinGL, operator!=, operator%, operator%=, operator*, operator*=, operator+, operator+=, operator-, operator-=, operator/, operator/=, operator=, operator==, MinGL::setWindowPosition, MinGL::setWindowSize.
void nsGraphics::Vec2D::setX(int x)
Définit la nouvelle position X (abscisse)
x : Nouvelle position X
Referenced by clavier, events.
int nsGraphics::Vec2D::getY() const
Récupère la position Y (ordonnée)
Une référence constante vers m_y
Referenced by clavier, nsGui::Text::draw, events, isColliding, min, MinGL::MinGL, operator!=, operator%, operator%=, operator*, operator*=, operator+, operator+=, operator-, operator-=, operator/, operator/=, operator=, operator==, MinGL::setWindowPosition, MinGL::setWindowSize.
void nsGraphics::Vec2D::setY(int y)
Définit la nouvelle position Y (ordonnée)
y : Nouvelle position Y
Referenced by clavier, events.
static Vec2D nsGraphics::Vec2D::min(const Vec2D &p1, const Vec2D &p2)
Retourne le vecteur le plus petit entre les deux passés en argument.
p1 : Premier vecteur p2 : Second vecteur
References getX, getY.
static bool nsGraphics::Vec2D::minf(const Vec2D &p1, const Vec2D &p2)
Retourne vrai si le premier vecteur est le plus petit des deux.
p1 : Premier vecteur p2 : Second vecteur
std::ostream & nsGraphics::Vec2D::_Edit(std::ostream &os=std::cout) const override
Fonction appelée pour injecter l'objet courant dans un flux.
os : Flux dans lequel injecter