MinGL
typedef std::pair<unsigned, bool> MinGL::KeyType_t
KeyType_t : Représente une touche du clavier.
C'est une paire de nombre entier naturel et booléen L'entier naturel représente le caractère pour une touche non spéciale, ou l'identifiant de touche pour une touche spéciale (Voir ici pour les identifiants). Le booléen indique si la touche est spéciale ou non.
typedef std::map<KeyType_t, bool> MinGL::KeyMap_t
KeyMap_t : Map représentant des touches et leurs état (pressée ou non).
La clé de cette map est un KeyType_t représentant une touche, et la valeur est son état.
std::string MinGL::m_windowName
m_windowName : Nom de la fenêtre
nsGraphics::RGBAcolor MinGL::m_bgColor
m_bgColor : Couleur de fond de la fenêtre
KeyMap_t MinGL::m_keyboardMap
m_keyboardMap : Map de l'état des touches du clavier
short MinGL::m_glutWindowId
m_glutWindowId : Identifiant de la fenêtre freeglut
nsEvent::EventManager MinGL::m_eventManager
m_eventManager : Gestionnaire d'évènements
bool MinGL::m_windowIsOpen
m_windowIsOpen : Etat de la fenêtre
MinGL::MinGL(const std::string &name, const nsGraphics::Vec2D &windowSize=nsGraphics::Vec2D(640, 480), const nsGraphics::Vec2D &windowPosition=nsGraphics::Vec2D(128, 128), const nsGraphics::RGBAcolor &backgroundColor=nsGraphics::KWhite)
Constructeur pour la classe MinGL.
name : Nom de la fenêtre windowSize : Taille de la fenêtre windowPosition : Position de la fenêtre backgroundColor : Couleur de fond de la fenêtre
References nsGraphics::Vec2D::getX, nsGraphics::Vec2D::getY.
MinGL::~MinGL()
Destructeur de la classe MinGL.
References stopGraphic.
void MinGL::initGraphic()
Initialise minGL et ouvre la fenêtre.
References BIND_CALLBACK, clearScreen, nsGraphics::RGBAcolor::getAlpha, nsGraphics::RGBAcolor::getBlue, nsGraphics::RGBAcolor::getGreen, nsGraphics::RGBAcolor::getRed.
Referenced by main, ppal.
void MinGL::stopGraphic()
Ferme la fenêtre et minGL proprement.
Referenced by ~MinGL.
bool MinGL::isPressed(const KeyType_t &key)
Renvoie l'état d'une touche du clavier (pressée ou non)
key : Touche du clavier a vérifier
Referenced by clavier, main.
void MinGL::resetKey(const KeyType_t &key)
Force une touche a être relâchée.
key : Touche du clavier a relâcher
Referenced by main.
void MinGL::finishFrame()
Préviens minGL que la frame est terminée.
Referenced by Credits, GameLoop, main, MenuP, Options, Pause.
void MinGL::clearScreen()
Efface l'écran avec la couleur de fond spécifiée.
Referenced by GameLoop, initGraphic, main, MenuP, Options.
nsEvent::EventManager & MinGL::getEventManager()
Récupère le gestionnaire d'évènements minGL.
Referenced by Credits, events, GameLoop, main, MenuP, Options, Pause.
const nsGraphics::RGBAcolor & MinGL::getBackgroundColor() const
Récupère la couleur de fond de la fenêtre.
void MinGL::setBackgroundColor(const nsGraphics::RGBAcolor &backgroundColor)
Règle la couleur de fond de la fenêtre.
References nsGraphics::RGBAcolor::getAlpha, nsGraphics::RGBAcolor::getBlue, nsGraphics::RGBAcolor::getGreen, nsGraphics::RGBAcolor::getRed.
nsGraphics::Vec2D MinGL::getWindowSize() const
Récupère la taille de la fenêtre.
void MinGL::setWindowSize(const nsGraphics::Vec2D &windowSize)
Règle la taille de la fenêtre.
windowSize : Nouvelle taille
References nsGraphics::Vec2D::getX, nsGraphics::Vec2D::getY.
nsGraphics::Vec2D MinGL::getWindowPosition() const
Récupère la position de la fenêtre.
void MinGL::setWindowPosition(const nsGraphics::Vec2D &windowPosition)
Règle la position de la fenêtre.
windowPosition : Nouvelle position
References nsGraphics::Vec2D::getX, nsGraphics::Vec2D::getY.
const std::string & MinGL::getWindowName() const
Récupère le nom de la fenêtre.
void MinGL::setWindowName(const std::string &windowName)
Règle le nom de la fenêtre.
windowName : Nouveau nom
bool MinGL::isOpen() const
Retourne si la fenêtre est ouverte.
Referenced by GameLoop, main.
static void MinGL::initGlut()
Initialise la bibliothèque freeglut.
Referenced by main, ppal.
void MinGL::callReshape(int h, int w)
Handler lié a glutReshapeFunc
h : Nouvelle hauteur de la fenêtre w : Nouvelle largeur de la fenêtre
void MinGL::callDisplay()
Handler lié a glutDisplayFunc
void MinGL::callMouse(int button, int state, int x=0, int y=0)
Handler lié a glutMouseFunc
button : Bouton de la souris qui a généré l'évènement state : Nouvel état du bouton x : Coordonnée X du curseur y : Coordonnée Y du curseur
void MinGL::callMotion(int x, int y)
Handler lié a glutMotionFunc
x : Coordonnée X du curseur y : Coordonnée Y du curseur
void MinGL::callPassiveMotion(int x, int y)
Handler lié a glutPassiveMotionFunc
x : Coordonnée X du curseur y : Coordonnée Y du curseur
void MinGL::callKeyboard(unsigned char key, int x=0, int y=0)
Handler lié a glutKeyboardFunc
key : Touche qui a été pressée x : Coordonnée X du curseur y : Coordonnée Y du curseur
void MinGL::callKeyboardUp(unsigned char key, int x=0, int y=0)
Handler lié a glutKeyboardUpFunc
key : Touche qui a été relâchée x : Coordonnée X du curseur y : Coordonnée Y du curseur
void MinGL::callKeyboardSpecial(int key, int x=0, int y=0)
Handler lié a glutSpecialFunc
key : Touche spéciale qui a été pressée x : Coordonnée X du curseur y : Coordonnée Y du curseur
void MinGL::callKeyboardUpSpecial(int key, int x=0, int y=0)
Handler lié a glutSpecialUpFunc
key : Touche spéciale qui a été relâchée x : Coordonnée X du curseur y : Coordonnée Y du curseur
void MinGL::callClose()
Handler lié a glutCloseFunc