nsAudio::AudioEngine
std::list<std::pair<std::string, sf::SoundBuffer> > nsAudio::AudioEngine::m_buffers
m_buffers : Liste des buffers utilisés par les éléments de m_sounds
std::list<sf::Sound> nsAudio::AudioEngine::m_sounds
m_sounds : Liste des effets audio en cours de lecture depuis des buffers
std::list<sf::Music> nsAudio::AudioEngine::m_soundsFromFiles
m_soundsFromFiles : Liste des effets audio en cours de lecture depuis des fichiers
sf::Music nsAudio::AudioEngine::m_music
m_music : Musique principale
void nsAudio::AudioEngine::setMusic(const std::string &fileName, bool loop=true)
Définit le fichier audio de la musique.
fileName : nom du fichier loop : indique si la musique est lue en boucle ou non (oui par défaut)
References nsException::KFileError.
Referenced by main.
void nsAudio::AudioEngine::toggleMusicPlaying()
Met en pause ou relance la musique.
Referenced by main.
void nsAudio::AudioEngine::setMusicPlaying(bool playing)
Règle l'état de lecture de la musique.
playing : Nouvel état de lecture
bool nsAudio::AudioEngine::isMusicPlaying() const
Récupère l'état de lecture de la musique.
Referenced by main.
void nsAudio::AudioEngine::loadSound(const std::string &fileName)
Charge un fichier audio dans un buffer.
References nsException::KFileError.
Referenced by main.
void nsAudio::AudioEngine::removeBuffer(const std::string &fileName)
Retire un buffer de la liste.
References nsException::KErrArg.
void nsAudio::AudioEngine::emptyBufferList()
Vide la liste des buffers.
void nsAudio::AudioEngine::startMusicFromBeginning()
Relance la musique depuis le début.
Referenced by main.
void nsAudio::AudioEngine::playSoundFromBuffer(const std::string &fileName)
Joue un son depuis un buffer.
fileName : nom du fichier
References nsException::KErrArg.
Referenced by main.
void nsAudio::AudioEngine::playSoundFromFile(const std::string &fileName)
Joue un son depuis un fichier.
fileName : nom du fichier
References nsException::KFileError.
void nsAudio::AudioEngine::removeOldSounds()
Retire les sons terminés des listes m_sounds et m_soundsFromFiles.