game.cpp
FPS_LIMIT
bool IsMoveLegal(const CMat &Mat, const bool &KeyUp, const bool &KeyDown, const bool &KeyRight, const bool &KeyLeft, const CPosition &Pos, const CMyParamV2 &Param)
References Color, KColor, CMyParamV2::NbColumn, CMyParamV2::NbRow.
Referenced by GameLoop.
pair< char, CPosition > nextMove(const CMat &Mat, const bool &KeyUp, const bool &KeyDown, const bool &KeyRight, const bool &KeyLeft, const CPosition &Pos, const CMyParamV2 &Param, CPosition &Tp1, CPosition &Tp2)
References CMyParamV2::NbColumn, CMyParamV2::NbRow.
Referenced by GameLoop.
bool IsCollectible(const char move)
Referenced by GameLoop.
void CalculateScore(vector< char > &objets, int &score)
Referenced by GameLoop.
void Sprite(MinGL &window, int grid_x, int grid_y, int pos_x, int pos_y, int mat_x, int mat_y, string sprite)
References Cigarette, Kebab, Monstre, Player1, Player2, Statue, Teleporter, Wall.
Referenced by DisplayGrid.
void DisplayGrid(MinGL &window, const CMat &mat, tuple< int, int > Screen_size)
References nsGraphics::KBlueTransparent, Sprite.
Referenced by GameLoop.
void MoveToken(CMat &Mat, const bool &KeyUp, const bool &KeyDown, const bool &KeyRight, const bool &KeyLeft, CPosition &Pos, CPosition &Tp1, CPosition &Tp2)
References KEmpty.
Referenced by GameLoop.
void MenuP(MinGL &window, vector< tuple< vector< int >, vector< int >, int > > clickablepool, tuple< int, int > Screen_size, int &menuid, chrono::time_point< chrono::steady_clock > start)
References nsEvent::EventManager::clearEvents, MinGL::clearScreen, events, MinGL::finishFrame, FPS_LIMIT, MinGL::getEventManager, InterfaceMenuP.
Referenced by ppal.
void Options(MinGL &window, vector< tuple< vector< int >, vector< int >, int > > clickablepool, tuple< int, int > Screen_size, int &menuid, chrono::time_point< chrono::steady_clock > start)
References nsEvent::EventManager::clearEvents, MinGL::clearScreen, events, MinGL::finishFrame, FPS_LIMIT, MinGL::getEventManager, InterfaceOptions.
Referenced by ppal.
void Credits(MinGL &window, vector< tuple< vector< int >, vector< int >, int > > clickablepool, tuple< int, int > Screen_size, int &menuid, chrono::time_point< chrono::steady_clock > start)
References nsEvent::EventManager::clearEvents, events, MinGL::finishFrame, FPS_LIMIT, MinGL::getEventManager, InterfaceCredits.
Referenced by ppal.
void Pause(MinGL &window, vector< tuple< vector< int >, vector< int >, int > > clickablepool, tuple< int, int > Screen_size, int &menuid, chrono::time_point< chrono::steady_clock > start)
References nsEvent::EventManager::clearEvents, events, MinGL::finishFrame, FPS_LIMIT, MinGL::getEventManager, InterfacePause.
Referenced by ppal.
void GameLoop(MinGL &window, vector< tuple< vector< int >, vector< int >, int > >clickablepool, CMat Mat, int menuid, unsigned PartyNum, bool Key1_UP, bool Key1_DOWN, bool Key1_RIGHT, bool Key1_LEFT, bool Key2_UP, bool Key2_DOWN, bool Key2_RIGHT, bool Key2_LEFT, tuple< int, int > Screen_size, CMyParamV2 param, bool Victory, unsigned KMaxPartyNum, CPosition PosPlayer1, CPosition PosPlayer2, CPosition PosTP1, CPosition PosTP2, bool Player1Turn, pair< char, CPosition > N_move1, pair< char, CPosition > N_move2, vector< char > objetJ1, vector< char > objetJ2, int scoreJ1, int scoreJ2, vector< CPosition > PosMonster)
References CalculateScore, nsEvent::EventManager::clearEvents, MinGL::clearScreen, Color, DisplayGrid, events, MinGL::finishFrame, FPS_LIMIT, MinGL::getEventManager, InitGrid, IsCollectible, IsMoveLegal, MinGL::isOpen, nsGraphics::KBlue, KColor, KEmpty, CMyParamV2::Key1Down, CMyParamV2::Key1Left, CMyParamV2::Key1Right, CMyParamV2::Key1Up, CMyParamV2::Key2Down, CMyParamV2::Key2Left, CMyParamV2::Key2Right, CMyParamV2::Key2Up, MoveMonster, MoveToken, CMyParamV2::NbColumn, CMyParamV2::NbRow, nextMove, CMyParamV2::tokenP1, CMyParamV2::tokenP2.
Referenced by ppal.
int ppal(void)
new main
0 if everything is OK
References Credits, GameLoop, MinGL::initGlut, MinGL::initGraphic, InitGrid, initParams, nsGraphics::KWhite, LoadParams, MenuP, CMyParamV2::NbColumn, CMyParamV2::NbRow, Options, Pause.
Referenced by main.