nsGraphics::RGBAcolor
GLubyte nsGraphics::RGBAcolor::m_red
m_red : Taux de rouge
GLubyte nsGraphics::RGBAcolor::m_green
m_green : Taux de vert
GLubyte nsGraphics::RGBAcolor::m_blue
m_blue : Taux de bleu
GLubyte nsGraphics::RGBAcolor::m_alpha
m_alpha : Taux de transparence
nsGraphics::RGBAcolor::RGBAcolor(const GLubyte &red=0, const GLubyte &green=0, const GLubyte &blue=0, const GLubyte &alpha=255)
Constructeur pour la classe RGBAcolor.
red : Taux de rouge (0-255) green : Taux de vert (0-255) blue : Taux de bleu (0-255) alpha : Taux de transparence (0-255)
nsGraphics::RGBAcolor::~RGBAcolor() override=default
Destructeur virtuel pour la classe RGBAcolor.
bool nsGraphics::RGBAcolor::operator==(const RGBAcolor &col) const
Opérateur d'égalité
col : Couleur a vérifier
bool nsGraphics::RGBAcolor::operator!=(const RGBAcolor &col) const
Opérateur d'inégalité
col : Couleur a vérifier
RGBAcolor nsGraphics::RGBAcolor::operator+(const RGBAcolor &rhs) const
Opérateur de décalage.
rhs : Couleur a additionner
RGBAcolor nsGraphics::RGBAcolor::operator*(const float &rhs) const
Opérateur de réduction.
rhs : Couleur avec laquelle multiplier la couleur actuelle
GLubyte nsGraphics::RGBAcolor::getRed() const
Récupère le taux de rouge.
Une référence constante vers m_red
Referenced by nsShape::Line::draw, nsShape::Rectangle::draw, nsShape::Triangle::draw, nsShape::Oval::draw, nsShape::Circle::draw, nsGui::Sprite::draw, BgText::getValues, MinGL::setBackgroundColor.
void nsGraphics::RGBAcolor::setRed(const GLubyte &red)
Définit le nouveau taux de rouge.
red : Nouveau taux de rouge
GLubyte nsGraphics::RGBAcolor::getGreen() const
Récupère le taux de vert.
Une référence constante vers m_green
Referenced by nsShape::Line::draw, nsShape::Rectangle::draw, nsShape::Triangle::draw, nsShape::Oval::draw, nsShape::Circle::draw, nsGui::Sprite::draw, BgText::getValues, MinGL::setBackgroundColor.
void nsGraphics::RGBAcolor::setGreen(const GLubyte &green)
Définit le nouveau taux de vert.
red : Nouveau taux de vert
GLubyte nsGraphics::RGBAcolor::getBlue() const
Récupère le taux de bleu.
Une référence constante vers m_blue
Referenced by nsShape::Line::draw, nsShape::Rectangle::draw, nsShape::Triangle::draw, nsShape::Oval::draw, nsShape::Circle::draw, nsGui::Sprite::draw, BgText::getValues, MinGL::setBackgroundColor.
void nsGraphics::RGBAcolor::setBlue(const GLubyte &blue)
Définit le nouveau taux de bleu.
red : Nouveau taux de bleu
GLubyte nsGraphics::RGBAcolor::getAlpha() const
Récupère le taux de transparence.
Une référence constante vers m_alpha
Referenced by nsShape::Line::draw, nsShape::Rectangle::draw, nsShape::Oval::draw, nsShape::Triangle::draw, nsShape::Circle::draw, nsGui::Sprite::draw, MinGL::setBackgroundColor.
void nsGraphics::RGBAcolor::setAlpha(const GLubyte &alpha)
Définit le nouveau taux de transparence.
red : Nouveau taux de transparence
std::ostream & nsGraphics::RGBAcolor::_Edit(std::ostream &os=std::cout) const override
Fonction appelée pour injecter l'objet courant dans un flux.
os : Flux dans lequel injecter